Increment13 0 1
dimsonson/go-yp-shortener-url pull request #20
Opened 2022-10-18 18:33 UTC by dimsonson

2022-10-23 14:30 UTC, lostsequence requested changes

2022-10-23 14:30 UTC, lostsequence commented on internal/app/handlers/handlers.go
> +	}
Всю логику работы с куками лучше перенести в middlware, много повторяющегося кода

2022-10-23 14:30 UTC, lostsequence commented on internal/app/handlers/handlers.go
> +	handler Services
Надо переименовать в service, а то получается что handler обращается к handler )

2022-10-23 14:30 UTC, lostsequence commented on internal/app/storage/storagefs.txt
> +
Удали файлик и в гит игнор

2022-10-23 14:30 UTC, lostsequence commented on internal/app/httprouters/middlewaregzip.go
> +	return r.gzipBody.Close()
Закрыть gzipReader (еще с прошлого спринта)

2022-10-23 14:30 UTC, lostsequence commented on internal/app/httprouters/middlewaregzip.go
> +			}  */
Почистить везде ненужный код

2022-10-23 14:30 UTC, lostsequence commented on cmd/shortener/main.go
> +)
Константы где-то еще используются или только в main ? Если нет, то лучше сделать приватными

2022-10-23 14:30 UTC, lostsequence commented on cmd/shortener/main.go
> +	}
Можешь создание стора в отдельную функцию вынести и не будет вложенных if else.
Просте:
```
if dlink != "" { return ... }
if !govalidator.IsUnixFilePath(path) || govalidator.IsWinFilePath(path)) || path == "" { return ... }
return memoryStore
```

2022-10-23 14:30 UTC, lostsequence commented on cmd/shortener/main.go
> +		if (!govalidator.IsUnixFilePath(path) || govalidator.IsWinFilePath(path)) || path == "" {
сначала проверь path != "" и только потом isUnix, isWin. Кстати, isUnix/isWin как валидируют пустой path ?

2022-10-23 14:30 UTC, lostsequence commented on internal/app/handlers/handlerreceiveshorturl_test.go
> +
Тебя не смущает растущее число файлов с тестами ? Если появятся хендлеры отвечающие за другую сущность, то файлов с тестами будет очень много и легко среди них потеряться и запутаться.
Предлагаю все таки объединить их в один файл.

2022-10-23 14:30 UTC, lostsequence commented on internal/app/storage/storagesql.go
> +				q := `SELECT short_url FROM sh_urls WHERE  long_url = $1`
Лишний пробел после where

2022-10-23 14:30 UTC, lostsequence commented on internal/app/storage/storagesql.go
> +func (ms *StorageSQL) PutToStorage(ctx context.Context, userid int, key string, value string) (existKey string, err error) {
В данном случае думаю стиль с именованными возвращаемыми параметрами не очень подходит.
Тяжело понять когда и что возвращается из функции

2022-10-23 14:30 UTC, lostsequence commented on internal/app/storage/storagesql.go
> +				}
эта ошибка вернется выше или только залогируется и все ?

2022-10-23 14:30 UTC, lostsequence commented on internal/app/services/service.go
> +	}
Почему такая логика ? Если ошибка - то присвоить existing key
Вообще, то что putToStorage возвращает существующую запись - путает.
В каких случаях это делается, не понятно, пока не почитаешь код метода.

2022-10-23 14:30 UTC, lostsequence commented on internal/app/services/service.go
> +	return value, err
Вроде бы возвращаемые параметры именованные, но возвращаем value, err.
Часть функций с именованными возвращаемыми параметрами, часть нет, почему вообще решил писать в таком стиле ?)

2022-10-23 14:30 UTC, lostsequence commented on internal/app/handlers/handlers.go
> +	for _, v := range dc {
Всю логику по записи урлов в цикле надо перенести в стор и передать туда слайс урлов.
В сервисе выполняется еще много ненужной логики.
Так же это позволить записывать все урлы в транзакции.

2022-10-23 15:08 UTC, lostsequence commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusConflict)
Почему conflict ? Как мы это понимаем ?

2022-10-25 13:51 UTC, dimsonson commented on cmd/shortener/main.go
> +)
+

2022-10-25 13:56 UTC, dimsonson commented on cmd/shortener/main.go
> +		if (!govalidator.IsUnixFilePath(path) || govalidator.IsWinFilePath(path)) || path == "" {
+
как ок)

2022-10-25 16:11 UTC, dimsonson commented on cmd/shortener/main.go
> +	}
+

2022-10-25 16:39 UTC, dimsonson commented on internal/app/httprouters/middlewaregzip.go
> +	return r.gzipBody.Close()
+
закрыл и тело и ридер

2022-10-26 07:38 UTC, dimsonson commented on internal/app/handlers/handlers.go
> +	handler Services
+

2022-10-26 07:43 UTC, dimsonson commented on internal/app/storage/storagesql.go
> +				q := `SELECT short_url FROM sh_urls WHERE  long_url = $1`
+

Готово

2022-10-26 08:32 UTC, dimsonson commented on internal/app/services/service.go
> +	return value, err
+
сделал именованные (что бы не объявлять)
и указываю что возвращается

2022-10-26 08:34 UTC, dimsonson commented on internal/app/storage/storagesql.go
> +func (ms *StorageSQL) PutToStorage(ctx context.Context, userid int, key string, value string) (existKey string, err error) {
+ 
Готово 
Именованные + указываю, что возвращается

2022-10-26 08:47 UTC, dimsonson commented on internal/app/storage/storagesql.go
> +				}
+ 
только логгируется, возвращается только если ошибка UniqueViolation
вообще видимо буду переделывать

2022-10-26 08:55 UTC, dimsonson commented on internal/app/httprouters/middlewaregzip.go
> +			}  */
+ 
Готово

2022-10-28 08:14 UTC, dimsonson commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusConflict)
+ 
Сделал проверку на 23505

2022-11-01 19:56 UTC, lostsequence approved these changes

2022-11-01 19:56 UTC, lostsequence commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusConflict)
выглядит очень неочевидно. Лучше вернуть какую-то осмысленную ошибку.
ErrConflict или что-то в этом роде.
Сейчас просто магическое число

2022-11-01 19:56 UTC, lostsequence commented on internal/app/storage/storagesql.go
> +	return existKey, err
Можно от кучи if ов избавиться и не игнорировать ошибку:
```
if (err == nil) {
    return existingKey, err
}

if errors.As(err, &pgErr) && pgErr.Code == pgerrcode.UniqueViolation {
    q := `SELECT short_url FROM sh_urls WHERE long_url = $1`
    err := ms.PostgreSQL.QueryRow(ctx, q, value).Scan(&existKey)
    if err != nil {
         return "", err
     }
}

return "", err
```

2022-11-01 19:56 UTC, lostsequence commented on internal/app/storage/storagesql.go
> +	userid := ctx.Value(settings.CtxKeyUserID).(string)
этот момент обсудили, что не стоит брать значения из контекста в сторе
передай useId в метод

2022-11-01 19:56 UTC, lostsequence commented on internal/app/storage/storagesql.go
> +		}
сделай проверку по аналогии как я описал выше, не игнорируй ошибку

2022-11-01 19:56 UTC, lostsequence commented on internal/app/httprouters/middlewaregzip.go
> +	return r.gzipBody.Close()
закрыть надо в методе close, не вижу, что закрыто

2022-11-01 19:56 UTC, lostsequence commented on internal/app/storage/storagesql.go
> +	q := "INSERT INTO sh_urls VALUES ($1, $2, $3)"
Добавь, пожалуйста, транзакцию

2022-11-01 19:56 UTC, lostsequence commented on internal/app/settings/settings.go
> +}
Непонятно, почему модельки в settings. Лучше их в файл со структурами определить.
Лучше назвать Request и Response, вместо Decode и Encode

2022-11-01 19:56 UTC, lostsequence commented on internal/app/storage/storagesql.go
> +					q := `SELECT short_url FROM sh_urls WHERE long_url = $1`
для Batch не надо возвращать UniqueViolation (судя по заданию)
Можно воспользоваться опцией ON CONFLICT

2022-11-01 19:56 UTC, lostsequence commented on internal/app/settings/settings.go
> +const StorageTimeout = 300000 * time.Second
что такой большой таймаут ?)

2022-11-07 11:20 UTC, dimsonson commented on internal/app/storage/storagesql.go
> +	userid := ctx.Value(settings.CtxKeyUserID).(string)
теперь в 4 спринте идет в аргументах их хендлера

2022-11-07 11:22 UTC, dimsonson commented on internal/app/storage/storagesql.go
> +	q := "INSERT INTO sh_urls VALUES ($1, $2, $3)"
добавил в 4 спринте

2022-11-07 11:46 UTC, dimsonson commented on internal/app/settings/settings.go
> +}
изменил в 4 спринте

2022-11-07 11:47 UTC, dimsonson commented on internal/app/settings/settings.go
> +const StorageTimeout = 300000 * time.Second
поправил)

2022-11-08 07:34 UTC, dimsonson commented on internal/app/storage/storagesql.go
> +	return existKey, err
Укоротил)
Правда добавилась транзакция  и метод стал больше)

2022-11-08 07:39 UTC, dimsonson commented on internal/app/storage/storagesql.go
> +		}
Сделал в 4 спринте

2023-05-01 10:13 UTC, closed without merging