Iter17
dimsonson/go-yp-shortener-url pull request #25
Opened 2022-12-27 20:43 UTC by dimsonson

2022-12-28 20:24 UTC, lostsequence requested changes

2022-12-28 20:24 UTC, lostsequence commented on internal/app/handlers/bench_test.go
> +		// обнуляемтаймер бенчмарка и запукаем его
пробел после "обнуляем"

2022-12-28 20:24 UTC, lostsequence commented on internal/app/handlers/bench_test.go
> +	s := &servicemock.ServiceMock{}
а что бенчмаркаем, если сервис замокан ? Основная логика же внутри сервиса

2022-12-28 20:24 UTC, lostsequence commented on internal/app/handlers/example_test.go
> +func Example() {
лучше разделить функции, чтобы было понятней какой хендлер что возвращает
и будет наглядней

2022-12-28 20:24 UTC, lostsequence commented on internal/app/handlers/delete.go
> +// Delete метод обработки DELETE запроса с слайсом short_url в теле
не хватает точек в конце описания в докстрингах, добавь пожалуйста везде

2022-12-28 20:24 UTC, lostsequence commented on internal/app/handlers/put.go
> +
Подскажи, а result0.pprof - это что за профиль ?

2022-12-28 20:28 UTC, lostsequence commented on internal/app/handlers/bench_test.go
> +		req := httptest.NewRequest(http.MethodPost, "/", strings.NewReader("http://ya.ru"))
Для бенчмарков по возможности генерят побольше данных

2022-12-31 10:09 UTC, dimsonson commented on internal/app/handlers/bench_test.go
> +	s := &servicemock.ServiceMock{}
Да, выделение памяти хендлерами. 
Основное выделение: json, body
Выбрана оптимизация выделения памяти при чтении Body.

Мне известны три варианта чтения Body в Go:
- NewScanner (result0)
- ReadAll (base)
- Copy (result)

Анализ профилей и алгоритмов работы этих трех вариантов выявил их поведение полностью соответсвующим заложенным в них алгоритмам:
- NewScanner (result0) - удвоение выделенной памяти при приближении к заполнению (аналогично работе map), в случае с Body избыточно
- ReadAll (base) - так же достаточно агрессивное выделение памяти, аналогично выделени памяти в слайсах, которые в общем то и есть под капотом ReadAll 
- Copy (result) - самый эффективный вариант по памяти, да и по производительности тоже. Благодоря sync.Pool, переиспользованию памяти в пуле и особенностям работы сборщика мусора.

2022-12-31 10:10 UTC, dimsonson commented on internal/app/handlers/bench_test.go
> +	s := &servicemock.ServiceMock{}
.+ готово

2022-12-31 10:10 UTC, dimsonson commented on internal/app/handlers/bench_test.go
> +		req := httptest.NewRequest(http.MethodPost, "/", strings.NewReader("http://ya.ru"))
.+ готово

2022-12-31 10:11 UTC, dimsonson commented on internal/app/handlers/bench_test.go
> +		// обнуляемтаймер бенчмарка и запукаем его
.+ готово

2022-12-31 10:11 UTC, dimsonson commented on internal/app/handlers/delete.go
> +// Delete метод обработки DELETE запроса с слайсом short_url в теле
.+ готово

2022-12-31 10:25 UTC, dimsonson commented on internal/app/handlers/put.go
> +
Это профиль при выделении памяти через NewScanner (удвоение как в map)

2022-12-31 10:25 UTC, dimsonson commented on internal/app/handlers/put.go
> +
.+ готово

2022-12-31 11:06 UTC, dimsonson commented on internal/app/handlers/example_test.go
> +func Example() {
.+ готово

2023-01-01 20:00 UTC, lostsequence approved these changes

2023-05-01 10:13 UTC, merged