Incriment3 1 1
dimsonson/go-yp-shortener-url pull request #5
Opened 2022-09-05 16:20 UTC by dimsonson

2022-09-09 14:48 UTC, lostsequence requested changes

2022-09-09 14:48 UTC, lostsequence commented on templates/index.html
> +
Не нашел, где используется данный файлик.
Если не нужен, лучше удалить.

2022-09-09 14:48 UTC, lostsequence commented on internal/app/handlers/handlerget.go
> +func GetHandler(w http.ResponseWriter, r *http.Request) {
Думаю, что лучше объединить Handlerget и Handlerpost в один хэндлер. Создать файлик, например, handler.go. Тогда вся логика работы хендлеров c URL будет в одном месте.
Туда поместить и обработчик post и обработчик get. И лучше переименовать postHandler в CreateURL/ShortenURL, например. Тогда нам будет понятно, чем конкретно данный обработчик занимается.
Тесты соответственно тоже перенести в один файлик.
Get тоже можно переименовать ) GetURL, например

2022-09-09 14:48 UTC, lostsequence commented on internal/app/server/httpserver.txt
> +
Этот файлик нужен ? Или можно удалить ?

2022-09-09 14:48 UTC, lostsequence commented on internal/app/httprouters/httprouter.go
> +	rout.Post("/*", handlers.PostHandler)
Надо мапить на конкретные пути.
Get("/*") -> Get("/{id}")
Post(/*) -> Post("/")

Насчет DefHandler - скорее всего он не нужен, потому что chi вернет 405 ошибку (если я правильно помню), если ничего не смаплено на роут.

2022-09-09 14:48 UTC, lostsequence commented on cmd/shortener/main.go
> +import (
По поводу файлов .DS_Store - надо их в gitignore добавить

2022-09-09 14:48 UTC, lostsequence commented on internal/app/handlers/handlerget_test.go
> +		{
Надо добавить еще кейс, когда url отсутствует

2022-09-09 14:48 UTC, lostsequence commented on internal/app/handlers/handlerget_test.go
> +			storage.DB["/xyz"] = "https://pkg.go.dev/github.com/stretchr/testify@v1.8.0/assert#Containsf"
Немного странный тест.
Нам надо протестировать случай, когда по ключу "xyz" вернётся "https://pkg.go.dev/github.com/stretchr/testify@v1.8.0/assert#Containsf" , мы проверяем просто "https://"

Чтобы в chi передать параметр "id", можно использовать контекст:
```
rctx := chi.NewRouteContext()
rctx.URLParams.Add("id", tc.id)
r = r.WithContext(context.WithValue(r.Context(), chi.RouteCtxKey, rctx))
```

2022-09-09 14:48 UTC, lostsequence commented on internal/app/handlers/handlerget.go
> +	value, ok := storage.DB[r.URL.Path]
Использовать URL.Path как ключ не стоит.
По заданию мы передаем параметр id в URL (посмотри коммет по хендлерам)
В get мы должны достать параметр с помощью chi.URLParam и уже его использовать в качестве ключа

2022-09-09 14:48 UTC, lostsequence commented on internal/app/handlers/handlerpost.go
> +	}
Метод проверять не надо, потому что мы мапим данный хендлер в роутере на POST

2022-09-09 14:48 UTC, lostsequence commented on internal/app/handlers/handlerpost.go
> +	}
Достаточно ресурсоёмкая операция.
Можно сгенерить рандомное число и добавить какую-то уникальную часть. Например, длину мапы, она всегда будет отличаться, так как если адреса нет, мы добавим новый и длина увеличится на 1. То есть для новой записи будет уникальный ключ.

2022-09-09 14:48 UTC, lostsequence commented on internal/app/handlers/handlerpost.go
> +	}
Перед тем как создать ключ, лучше добавить валидацию URL и убедиться, что URL корректный.
Можно восмользоваться методами:
Parse или ParseRequestURI

Добавить test case, где URL будет неправильный

2022-09-09 19:01 UTC, dimsonson commented on templates/index.html
> +
Хорошо

2022-09-09 19:02 UTC, dimsonson commented on internal/app/server/httpserver.txt
> +
Удаляю...

2022-09-09 19:05 UTC, dimsonson commented on cmd/shortener/main.go
> +import (
Добавил

2022-09-10 07:54 UTC, dimsonson commented on internal/app/handlers/handlerpost.go
> +	}
Не совсем понял комментарий...

Ты посмотрел функцию randomsuff.RandSeq() ?

Там как раз генерируется рандомное число (на самом деле они все псевдо рандомные), к нему добавляется юникстайм момента генерации и формируется суффикс из занков английского алфавита заданной длинны.

Ты про то, что проверку на уникальность можно не делать совсем?
Я ее сделал потому что на самом деле это псевдорамдомные числа и у них есть вероятность повторения.

Убрать проверку, достачно randomsuff.RandSeq() ?

2022-09-10 09:09 UTC, lostsequence commented on internal/app/handlers/handlerpost.go
> +	}
Да, видел :)
Просто нет гарантий, что не будет повторений ключа (ведь не зря делаем проверку на уникальность)
Но можно добавить к рандомному ключу длину мапы, например. Она гарантированно уникальна.
Ну или можно использовать готовые хеш функции ) они защищены от коллизий и всегда возвращают один и тот же кеш для одной и той же стринги

2022-09-10 17:11 UTC, dimsonson commented on internal/app/handlers/handlerpost.go
> +	}
Возможно я что то не понимаю)

Смущают два момента:
1. Эти вариант хеш хорош для уникальности, но из них не получится желаемая бизнес-цель - короткий URL.
Если я правильно понимаю хеш функции возвращают от 20 знаков (SHA-1). Если речь идет о добавлении к сгенерированному псевдослучвйному ключу числа длинны мапы, даже при 1 млн. ссылок это будет плюс 7 знаков, а к примеру у яндекса сервис выдает 5 знаков всего.
2. Если речь идет о генерации ключа с seed в значении длинны мапы, то эту функцию так же выполняет количство секунд прошедших с 01.01.1970 на момент генерации.

Получается, что если идея в том, что бы отказаться от проверки на уникальность через генерацию уже уникальных значений, то это уже реализованно и нужно просто убрать проверку на уникальность.

Что я думаю не так?)

2022-09-10 17:14 UTC, dimsonson commented on internal/app/handlers/handlerpost.go
> +	}
Точно)

2022-09-11 12:31 UTC, dimsonson commented on internal/app/handlers/handlerget.go
> +func GetHandler(w http.ResponseWriter, r *http.Request) {
Зачем в один хендлер?
Это обязательно? Какой смысл?
Так можно все в main написать)

2022-09-11 16:25 UTC, dimsonson commented on internal/app/handlers/handlerget_test.go
> +		{
Добавил

2022-09-11 16:26 UTC, dimsonson commented on internal/app/handlers/handlerget_test.go
> +			storage.DB["/xyz"] = "https://pkg.go.dev/github.com/stretchr/testify@v1.8.0/assert#Containsf"
Да, передал)

2022-09-11 16:34 UTC, dimsonson commented on internal/app/httprouters/httprouter.go
> +	rout.Post("/*", handlers.PostHandler)
Условие:
Нужно учесть некорректные запросы и возвращать для них ответ с кодом 400.

Поучается все же нужен для возврата ошибки 400 ?

2022-09-14 12:57 UTC, lostsequence requested changes

2022-09-14 12:57 UTC, lostsequence commented on cmd/shortener/main.go
> +	fmt.Printf("Started server on port %s\n", addr)
Тут лучше тоже использовать "log", log нам выведет timestamp и так же мы можем вывести инфу не только в stdout, но и в другие потоки (файл, например)
И тут лучше писать тогда: "Starting" , потому что он только запускается и мы не знаем, запустился он или нет.

2022-09-14 12:57 UTC, lostsequence commented on internal/app/handlers/incorrectreq.go
> +	http.Error(w, "request incorect", http.StatusBadRequest)
"incorrect"

2022-09-14 12:57 UTC, lostsequence commented on internal/app/handlers/createshort.go
> +func CreateShortURL(w http.ResponseWriter, r *http.Request) {
Решил не объединять логику в один файл ? Сейчас в принципе не страшно, но когда будешь работать не с одной сущностью, а с несколькими и хендлеров будет больше чем 2 на сущность, тогда можно запутаться :)

2022-09-14 12:57 UTC, lostsequence commented on internal/app/handlers/handlerget_test.go
> +			h.ServeHTTP(w, r)
Можно в принципе обойтись без handlerFun и serveHttp, просто вызвать функцию хендлера:
`handlers.GetShortURL(w, r)`

Аналогично для теста create

2022-09-14 12:57 UTC, lostsequence commented on internal/app/handlers/handlerget_test.go
> +
можно файлик назвать аналогично 'createshort_test' - 'getshort_test'

2022-09-14 12:57 UTC, lostsequence commented on internal/app/httprouters/httprouter.go
> +	//rout.HandleFunc("/", handlers.IncorrectRequests)
закоменченный код нужен ?)

2022-09-14 12:57 UTC, lostsequence commented on cmd/shortener/main.go
> +	//httprouters.NewRouter()
закоменченный код нужен ?)

2022-09-14 12:57 UTC, lostsequence commented on internal/app/randomsuff/randomsuff.go
> + */
закоменченный код нужен ?)

2022-09-14 12:57 UTC, lostsequence commented on internal/app/handlers/createshort.go
> +	}
тут я имел в виду что-то вроде такого сделать:
```
tmpKey, err := randomsuff.RandSeq(settings.KeyLeght)
if err != nil {
  log.Fatal(err) //RandSeq настраивается на этапе запуска http сервера
}
unique := len(storage.DB) // уникальная часть
shortId := fmt.Sprintf("%s%d", tmpKey, unique) // рандом + уникальная часть
```

2022-09-14 12:57 UTC, lostsequence commented on internal/app/settings/settings.go
> +const KeyLeght int = 5 //значение должно быть больше 0
Добавь пожалуйста newline где это требуется ) (красный круг в гите)

2022-09-14 14:22 UTC, dimsonson commented on internal/app/handlers/createshort.go
> +func CreateShortURL(w http.ResponseWriter, r *http.Request) {
Сделаю на втором спринте)
Уже есть заготовка в другом PR )

2022-09-22 19:12 UTC, lostsequence approved these changes
Поправь несколько комментов ко второму спринту :)

2022-09-22 19:12 UTC, lostsequence commented on internal/app/handlers/createshort_test.go
> +			if resp.Header.Get("Content-Type") != tt.want.contentType {
Используй assert, как на 80 строке

2022-09-22 19:12 UTC, lostsequence commented on internal/app/handlers/createshort_test.go
> +			resBody, err := io.ReadAll(resp.Body)
Можно из "w" взять байтики: `w.Body.Bytes()` и не использовать ReadAll

2022-09-22 19:12 UTC, lostsequence commented on internal/app/handlers/createshort_test.go
> +			if resp.StatusCode != tt.want.code {
Используй assert, как на 80 строке

2022-09-22 19:12 UTC, lostsequence commented on internal/app/handlers/createshort_test.go
> +			h.ServeHTTP(w, request)
В принципе можно без ServeHTTP и HandlerFunc.
Просто вызвать метод хендлера:
`handlers.CreateShortURL(w, request)`

2022-09-22 19:12 UTC, lostsequence commented on internal/app/handlers/createshort_test.go
> +			name: "POST #1",
Задай, пожалуйста, осмысленные имена к тестам: "Successful URL creation", "Invalid URL" или что-то в этом роде.

2022-09-22 19:12 UTC, lostsequence commented on internal/app/handlers/getshort_test.go
> +			name: "GET #1",
Задай, пожалуйста, осмысленные имена к тестам, как и для POST tests

2022-09-22 19:12 UTC, lostsequence commented on internal/app/handlers/getshort.go
> +	}
Тут лучше проверить по другому, взять chi.URLParam(r, "id") и проверить пустая строка или нет:
```
id := chi.URLParam(r, "id")
if id == "" {
    http.Error(w, "userId is empty", http.StatusBadRequest)
    return
}
```

2022-09-27 05:09 UTC, merged